apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: demo
spec:
  containers:
  - image: docker.io/audomsak/spring-petclinic:openjdk-11.0.24-ubi8
    name: pod
