apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod
  name: pod
  namespace: first-gitops-space
spec:
  containers:
  - image: docker.io/audomsak/node-web:1.0
    name: pod
